"""Post-processing module to convert OpenDRIVE objects to signals.

This module converts traffic sign objects (as generated by netconvert) into
proper OpenDRIVE signals for compatibility with simulators like CARLA.

Also handles geoReference fixup for CARLA compatibility.
"""

from __future__ import annotations

import math
import re
import xml.etree.ElementTree as ET
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

import utm
from loguru import logger

try:
    import pyproj as _pyproj
except ImportError:
    _pyproj = None  # type: ignore[assignment]

# Country-specific Signal Mappings
# SE: Swedish Vägmärken, DE: German StVO (industry standard for CARLA/OpenDRIVE)
COUNTRY_MAPPINGS: dict[str, dict[str, str]] = {
    "SE": {
        "priority": "401",  # Priority road (Huvudled)
        "yield": "206",  # Yield / Give Way (Väjningsplikt)
        "stop": "201",  # Stop
        "right before left": "102",  # Danger: Crossroad
        "speedLimit": "274",  # Speed Limit
        "speed": "274",  # Generic speed limit
        "traffic_light": "1000001",  # Traffic signals (International)
        "no_entry": "267",  # No entry (Industry standard)
    },
    "DE": {
        "priority": "306",  # Priority road (Diamond sign)
        "yield": "205",  # Yield / Give Way
        "stop": "206",  # Stop
        "right before left": "102",  # Danger: Crossroad
        "speedLimit": "274",  # Speed Limit
        "speed": "274",  # Generic speed limit
        "traffic_light": "1000001",
        "no_entry": "267",
    },
}

# Default dimensions for different sign types (width, height) in meters
COUNTRY_DIMENSIONS: dict[str, dict[str, tuple[str, str]]] = {
    "SE": {
        "401": ("0.6", "0.6"),
        "206": ("0.9", "0.8"),
        "201": ("0.75", "0.75"),
        "102": ("0.7", "0.7"),
        "274": ("0.6", "0.6"),
        "1000001": ("0.3", "0.7"),  # Traffic light box
        "267": ("0.6", "0.6"),
    },
    "DE": {
        "306": ("0.6", "0.6"),
        "205": ("0.9", "0.8"),
        "206": ("0.75", "0.75"),
        "102": ("0.7", "0.7"),
        "274": ("0.6", "0.6"),
        "1000001": ("0.3", "0.7"),
        "267": ("0.6", "0.6"),
    },
}


@dataclass
class ConversionResult:
    """Result of a signal conversion operation."""

    success: bool
    signals_converted: int
    poles_added: int
    error: str | None = None


def fix_georeference_for_carla(xodr_file: Path) -> bool:
    """Fix geoReference to include explicit lat_0/lon_0 for CARLA compatibility.

    CARLA's geoReference parser only extracts +lat_0 and +lon_0 values from the
    projection string for geocoordinate conversions (GNSS sensor, transform_to_geolocation).
    Without these parameters, CARLA falls back to incorrect default values.

    This function calculates the correct lat_0/lon_0 based on the OpenDRIVE
    offset (x, y) and the UTM zone defined in the projection string.
    The <offset> element in OpenDRIVE represents the translation applied to
    the original coordinates to get the local coordinates (i.e. origin (0,0)).
    Therefore, the offset values correspond to the UTM coordinates of the map origin.

    Args:
        xodr_file: Path to the OpenDRIVE file.

    Returns:
        True if geoReference was updated, False otherwise.
    """
    try:
        tree = ET.parse(xodr_file)
        root = tree.getroot()
    except ET.ParseError as e:
        logger.error(f"Failed to parse {xodr_file}: {e}")
        return False

    header = root.find("header")
    if header is None:
        logger.warning(f"No <header> element found in {xodr_file}")
        return False

    # Extract offset (defaults to 0 if missing)
    offset_elem = header.find("offset")
    if offset_elem is not None:
        offset_x = float(offset_elem.get("x", "0"))
        offset_y = float(offset_elem.get("y", "0"))
    else:
        # Some versions might store it as attributes on header, but
        # standard is subelement. Default to 0 if not found.
        offset_x = 0.0
        offset_y = 0.0

    georef = header.find("geoReference")
    if georef is None:
        logger.warning(f"No <geoReference> element found in {xodr_file}")
        return False

    current = georef.text or ""
    current = current.strip()

    if not current:
        logger.warning(f"Empty geoReference in {xodr_file}")
        return False

    # Check if lat_0/lon_0 already present
    if "+lat_0=" in current and "+lon_0=" in current:
        logger.debug("geoReference already contains lat_0/lon_0")
        return False

    # Parse UTM zone from string
    # Expected format like "+proj=utm +zone=33 +ellps=WGS84..."
    zone_match = re.search(r"\+zone=(\d+)", current)
    if not zone_match:
        logger.warning(f"Could not parse UTM zone from geoReference: {current}")
        return False

    zone_number = int(zone_match.group(1))

    # Check for southern hemisphere
    is_northern = "+south" not in current

    try:
        # Convert Offset (UTM) to Lat/Lon
        # The offset x,y is the UTM coordinate of the map origin (0,0)
        lat_0, lon_0 = utm.to_latlon(offset_x, offset_y, zone_number, northern=is_northern)
    except utm.error.OutOfRangeError as e:
        logger.error(f"Failed to convert UTM to Lat/Lon: {e}")
        return False

    # Remove existing partial lat_0 or lon_0 if present
    current = re.sub(r"\+lat_0=[\d.-]+\s*", "", current)
    current = re.sub(r"\+lon_0=[\d.-]+\s*", "", current)
    current = current.strip()

    # Append lat_0 and lon_0 with high precision
    new_ref = f"{current} +lat_0={lat_0:.10f} +lon_0={lon_0:.10f}"

    # Preserve the original formatting with newlines
    georef.text = f"\n{new_ref}\n        "

    try:
        tree.write(xodr_file, encoding="UTF-8", xml_declaration=True)
        logger.info(
            f"Fixed geoReference for CARLA: lat_0={lat_0:.6f}, lon_0={lon_0:.6f} "
            f"(derived from offset x={offset_x:.2f}, y={offset_y:.2f})"
        )
        return True
    except Exception as e:
        logger.error(f"Failed to write {xodr_file}: {e}")
        return False


def _add_pole(objects_elem: ET.Element, source_obj: ET.Element) -> None:
    """Add a pole object for a given sign object.

    Args:
        objects_elem: Parent objects element to add pole to.
        source_obj: Source sign object to create pole for.
    """
    pole = ET.SubElement(objects_elem, "object")
    pole.set("id", source_obj.get("id", "") + ".pole")
    pole.set("type", "pole")
    pole.set("name", "Sign Pole")
    pole.set("s", source_obj.get("s", "0.0"))
    pole.set("t", source_obj.get("t", "0.0"))
    pole.set("zOffset", "0.0")
    pole.set("height", "2.0")
    pole.set("radius", "0.05")
    pole.set("dynamic", "no")
    pole.set("hdg", "0.0")
    pole.set("pitch", "0.0")
    pole.set("roll", "0.0")


def _get_mapping_key_from_poi(poi: ET.Element) -> str | None:
    """Resolve a POI to an internal mapping key used by COUNTRY_MAPPINGS."""
    poi_type = poi.get("type", "")
    if poi_type:
        return poi_type

    params = {param.get("key", ""): param.get("value", "") for param in poi.findall("param")}
    if params.get("osm.highway") == "give_way":
        return "yield"
    if params.get("osm.highway") == "stop":
        return "stop"
    if params.get("osm.highway") == "traffic_signals":
        return "traffic_light"
    return params.get("osm.traffic_sign")


def _get_sign_heading_offset_deg(params: dict[str, str]) -> float:
    """Return a sign heading offset, in degrees, from OSM params.

    For forward/backward directions the heading flip is handled entirely
    by the OpenDRIVE ``orientation`` attribute (see
    ``_get_signal_orientation``), so this function returns 0 for both.
    Numeric direction values are passed through as-is.
    """
    # Check for standard OSM direction tags
    direction = params.get("osm.direction") or params.get("osm.traffic_sign:direction")
    if direction is not None:
        direction = str(direction).strip().lower()

        # forward/backward are handled via orientation, not hOffset.
        if direction in ("forward", "backward"):
            return 0.0

        # Handle numeric direction
        try:
            return float(direction)
        except (TypeError, ValueError):
            pass

    return 0.0


def _get_signal_orientation(params: dict[str, str], t_value: float) -> str:
    """Determine the OpenDRIVE signal orientation ("+" or "-").

    When an explicit OSM ``direction`` tag is present the orientation is
    derived from it directly (the parent-way filtering in the caller
    ensures the sign is placed on a road whose s-direction matches the
    OSM way direction):

    * ``forward``  → ``"+"`` (signal applies to s-direction traffic)
    * ``backward`` → ``"-"`` (signal applies to traffic against s)

    When no direction tag exists, falls back to the conventional
    t-coordinate heuristic (``t < 0`` → ``"+"``).
    """
    direction = (
        (params.get("osm.direction") or params.get("osm.traffic_sign:direction") or "")
        .strip()
        .lower()
    )

    if direction == "forward":
        return "+"
    if direction == "backward":
        return "-"

    # No explicit direction: fall back to geometric t-coordinate convention.
    return "+" if t_value < 0 else "-"


def _load_poi_params_by_id(poi_file: Path | None) -> dict[str, dict[str, str]]:
    """Load POI param key/value pairs keyed by POI id."""
    if poi_file is None or not poi_file.exists():
        return {}

    try:
        poi_root = ET.parse(poi_file).getroot()
    except ET.ParseError:
        return {}

    params_by_id: dict[str, dict[str, str]] = {}
    for poi in poi_root.findall("poi"):
        poi_id = poi.get("id")
        if not poi_id:
            continue
        params_by_id[poi_id] = {
            param.get("key", ""): param.get("value", "") for param in poi.findall("param")
        }
    return params_by_id


def _project_point_to_segment(
    px: float,
    py: float,
    start: tuple[float, float, float],
    end: tuple[float, float, float],
) -> tuple[float, float, float]:
    """Project a point onto a planView segment.

    Returns:
        Tuple of (distance_to_segment, s_value, signed_t_value).
    """
    x0, y0, s0 = start
    x1, y1, s1 = end
    vx = x1 - x0
    vy = y1 - y0
    segment_length_sq = vx * vx + vy * vy
    if segment_length_sq == 0:
        distance = math.hypot(px - x0, py - y0)
        return distance, s0, 0.0

    projection_ratio = ((px - x0) * vx + (py - y0) * vy) / segment_length_sq
    projection_ratio = max(0.0, min(1.0, projection_ratio))

    projected_x = x0 + projection_ratio * vx
    projected_y = y0 + projection_ratio * vy
    dx = px - projected_x
    dy = py - projected_y
    distance = math.hypot(dx, dy)

    cross = vx * (py - y0) - vy * (px - x0)
    signed_t = distance if cross > 0 else -distance
    s_value = s0 + projection_ratio * max(s1 - s0, math.hypot(vx, vy))
    return distance, s_value, signed_t


def _build_road_reference_points(
    root: ET.Element,
) -> list[tuple[ET.Element, list[tuple[float, float, float]]]]:
    """Build road polyline reference points from planView geometry starts."""
    roads: list[tuple[ET.Element, list[tuple[float, float, float]]]] = []

    for road in root.findall("road"):
        plan_view = road.find("planView")
        if plan_view is None:
            continue

        points: list[tuple[float, float, float]] = []
        last_geom: ET.Element | None = None
        for geometry in plan_view.findall("geometry"):
            try:
                points.append(
                    (
                        float(geometry.get("x", "0")),
                        float(geometry.get("y", "0")),
                        float(geometry.get("s", "0")),
                    )
                )
                last_geom = geometry
            except ValueError:
                continue

        # Append the actual road endpoint computed from the last geometry's
        # heading and length.  Also extend another 20 m beyond that so signs
        # that fall inside a junction box (which netconvert trims the road
        # back into) can still be projected onto the correct road with a
        # realistic lateral offset.  The caller should clamp s to road length.
        if last_geom is not None and points:
            try:
                lx, ly, ls = points[-1]
                l_hdg = float(last_geom.get("hdg", "0"))
                l_len = float(last_geom.get("length", "0"))
                end_x = lx + l_len * math.cos(l_hdg)
                end_y = ly + l_len * math.sin(l_hdg)
                end_s = ls + l_len
                points.append((end_x, end_y, end_s))
                _JUNCTION_EXTENSION_M = 20.0
                points.append(
                    (
                        end_x + _JUNCTION_EXTENSION_M * math.cos(l_hdg),
                        end_y + _JUNCTION_EXTENSION_M * math.sin(l_hdg),
                        end_s + _JUNCTION_EXTENSION_M,
                    )
                )
            except ValueError:
                pass

        if len(points) >= 2:
            roads.append((road, points))

    return roads


def _get_utm_zone_number(root: ET.Element) -> int | None:
    """Extract the UTM zone number from the OpenDRIVE geoReference."""
    header = root.find("header")
    georef = header.find("geoReference") if header is not None else None
    georef_text = georef.text if georef is not None else ""
    if not georef_text:
        return None

    zone_match = re.search(r"\+zone=(\d+)", georef_text)
    if zone_match is None:
        return None

    return int(zone_match.group(1))


def _get_georef_proj_string(root: ET.Element) -> str | None:
    """Extract the raw projection string from the OpenDRIVE geoReference."""
    header = root.find("header")
    georef = header.find("geoReference") if header is not None else None
    if georef is None:
        return None
    text = (georef.text or "").strip()
    return text if text else None


def _make_latlon_to_local(
    root: ET.Element, offset_x: float, offset_y: float
) -> Callable[[float, float], tuple[float, float]] | None:
    """Build a callable that converts (lat, lon) → (local_x, local_y).

    Handles both ``+proj=utm`` and ``+proj=tmerc`` geoReferences.
    Falls back to UTM auto-zone when the zone cannot be determined.
    Returns *None* only if neither UTM nor pyproj can be used.
    """
    proj_str = _get_georef_proj_string(root)

    # tmerc projection (e.g. viewer-supplied +proj=tmerc +lat_0=... +lon_0=...)
    if proj_str and "+proj=tmerc" in proj_str and _pyproj is not None:
        try:
            proj = _pyproj.Proj(proj_str)

            def _tmerc(
                lat: float, lon: float, _proj=proj, _ox=offset_x, _oy=offset_y
            ) -> tuple[float, float]:
                x, y = _proj(lon, lat)  # pyproj takes (lon, lat) order
                return x - _ox, y - _oy

            return _tmerc
        except Exception as exc:
            logger.warning(f"Failed to build tmerc projector from '{proj_str}': {exc}")

    # Default: UTM (may auto-detect zone from lat/lon if zone_number is None)
    zone_number = _get_utm_zone_number(root)

    def _utm_convert(
        lat: float, lon: float, _zone=zone_number, _ox=offset_x, _oy=offset_y
    ) -> tuple[float, float]:
        easting, northing, _, _ = utm.from_latlon(float(lat), float(lon), force_zone_number=_zone)
        return easting - _ox, northing - _oy

    return _utm_convert


def _get_road_sumo_way_id(road: ET.Element) -> str | None:
    """Extract the source OSM way id from a road's SUMO userData, if present."""
    user_data = road.find("userData[@code='sumoId']")
    if user_data is None:
        return None

    sumo_id = user_data.get("value")
    if not sumo_id:
        return None

    return sumo_id.split("#", 1)[0]


def _load_osm_sign_parent_ways(osm_file: Path | None) -> dict[str, set[str]]:
    """Map OSM sign node ids to the source way ids that contain them."""
    if osm_file is None or not osm_file.exists():
        return {}

    root = ET.parse(osm_file).getroot()
    give_way_nodes = {
        node.get("id")
        for node in root.findall("node")
        if any(
            tag.get("k") == "highway" and tag.get("v") == "give_way" for tag in node.findall("tag")
        )
    }

    parent_ways: dict[str, set[str]] = {node_id: set() for node_id in give_way_nodes if node_id}
    for way in root.findall("way"):
        way_id = way.get("id")
        if not way_id:
            continue
        for node_ref in (nd.get("ref") for nd in way.findall("nd")):
            if node_ref in parent_ways:
                parent_ways[node_ref].add(way_id)

    return parent_ways


def _add_missing_poi_signals(
    root: ET.Element,
    poi_file: Path,
    country: str,
    osm_file: Path | None = None,
) -> tuple[int, int]:
    """Add signals for POIs that netconvert did not materialize as objects.

    This is a fallback path for signs near complex junctions and roundabouts,
    where SUMO may drop the polygon POI instead of turning it into a road object.
    """
    poi_tree = ET.parse(poi_file)
    poi_root = poi_tree.getroot()

    existing_signal_ids = {
        signal.get("id") for signal in root.findall(".//signal") if signal.get("id")
    }

    header = root.find("header")
    offset = header.find("offset") if header is not None else None
    offset_x = float(offset.get("x", "0")) if offset is not None else 0.0
    offset_y = float(offset.get("y", "0")) if offset is not None else 0.0
    latlon_to_local = _make_latlon_to_local(root, offset_x, offset_y)
    parent_ways = _load_osm_sign_parent_ways(osm_file)

    roads = _build_road_reference_points(root)
    mapping = COUNTRY_MAPPINGS.get(country.upper(), COUNTRY_MAPPINGS["SE"])
    dimensions = COUNTRY_DIMENSIONS.get(country.upper(), COUNTRY_DIMENSIONS["SE"])

    added_signals = 0
    added_poles = 0

    for poi in poi_root.findall("poi"):
        poi_id = poi.get("id")
        if not poi_id or poi_id in existing_signal_ids:
            continue

        mapping_key = _get_mapping_key_from_poi(poi)
        if not mapping_key or mapping_key not in mapping:
            continue

        params = {param.get("key", ""): param.get("value", "") for param in poi.findall("param")}

        lat = poi.get("lat")
        lon = poi.get("lon")
        if not lat or not lon:
            continue

        local_x, local_y = latlon_to_local(float(lat), float(lon))

        best_distance = float("inf")
        best_road: ET.Element | None = None
        best_s = 0.0
        best_t = 0.0

        preferred_way_ids = parent_ways.get(poi_id, set())
        candidate_roads = roads
        if preferred_way_ids:
            preferred_roads = [
                (road, points)
                for road, points in roads
                if _get_road_sumo_way_id(road) in preferred_way_ids
            ]
            if preferred_roads:
                candidate_roads = preferred_roads

        for road, points in candidate_roads:
            for start, end in zip(points, points[1:]):
                distance, s_value, t_value = _project_point_to_segment(
                    local_x,
                    local_y,
                    start,
                    end,
                )
                if distance < best_distance:
                    best_distance = distance
                    best_road = road
                    best_s = s_value
                    best_t = t_value

        if best_road is None or best_distance > 25.0:
            continue

        # Clamp s to road length: the virtual extension may produce s values
        # beyond the road end, which would be invalid in OpenDRIVE.
        road_length = float(best_road.get("length", str(best_s)))
        best_s = min(best_s, road_length)

        signals_elem = best_road.find("signals")
        if signals_elem is None:
            signals_elem = ET.SubElement(best_road, "signals")

        objects_elem = best_road.find("objects")
        if objects_elem is None:
            objects_elem = ET.SubElement(best_road, "objects")

        signal_type_id = mapping[mapping_key]
        width, height = dimensions.get(signal_type_id, ("0.5", "0.5"))

        signal = ET.SubElement(signals_elem, "signal")
        signal.set("id", poi_id)
        signal.set("type", signal_type_id)
        signal.set("name", mapping_key)
        signal.set("s", f"{best_s:.8f}")
        signal.set("t", f"{best_t:.8f}")
        signal.set("dynamic", "no")
        signal.set("zOffset", "2.0")
        signal.set("country", country.upper())
        signal.set("width", width)
        signal.set("height", height)
        orientation = _get_signal_orientation(params, best_t)
        h_offset_deg = _get_sign_heading_offset_deg(params)
        if orientation == "-":
            h_offset_deg += 180.0
        signal.set("hOffset", f"{math.radians(h_offset_deg):.8f}")
        signal.set("pitch", "0.0")
        signal.set("roll", "0.0")
        signal.set("orientation", orientation)

        pole = ET.SubElement(objects_elem, "object")
        pole.set("id", poi_id + ".pole")
        pole.set("type", "pole")
        pole.set("name", "Sign Pole")
        pole.set("s", f"{best_s:.8f}")
        pole.set("t", f"{best_t:.8f}")
        pole.set("zOffset", "0.0")
        pole.set("height", "2.0")
        pole.set("radius", "0.05")
        pole.set("dynamic", "no")
        pole.set("hdg", "0.0")
        pole.set("pitch", "0.0")
        pole.set("roll", "0.0")

        existing_signal_ids.add(poi_id)
        added_signals += 1
        added_poles += 1

    return added_signals, added_poles


def _process_signals(
    objects_elem: ET.Element,
    signals_elem: ET.Element,
    country: str = "SE",
    poi_params_by_id: dict[str, dict[str, str]] | None = None,
    parent_ways: dict[str, set[str]] | None = None,
    road_way_id: str | None = None,
) -> tuple[int, int]:
    """Convert traffic sign objects to OpenDRIVE signals.

    Args:
        objects_elem: Objects element containing sign objects.
        signals_elem: Signals element to add converted signals to.
        country: Country code for signal mapping.
        poi_params_by_id: Additional POI metadata keyed by id.
        parent_ways: Mapping of OSM node id to the set of parent way ids.
            When provided together with *road_way_id*, objects whose node id
            maps to a *different* way are skipped so that
            ``_add_missing_poi_signals`` can place them on the correct road.
        road_way_id: The source OSM way id of the current road (from SUMO userData).

    Returns:
        Tuple of (signals_converted, poles_added).
    """
    to_remove: list[ET.Element] = []
    converted_count = 0
    poles_count = 0

    # Get country-specific mapping
    mapping = COUNTRY_MAPPINGS.get(country.upper(), COUNTRY_MAPPINGS["SE"])
    dimensions = COUNTRY_DIMENSIONS.get(country.upper(), COUNTRY_DIMENSIONS["SE"])

    for obj in objects_elem.findall("object"):
        # Extract parameters (OSM tags stored via osm_extractor.py)
        params = {p.get("key", ""): p.get("value", "") for p in obj.findall("param")}
        poi_params = (poi_params_by_id or {}).get(obj.get("id", ""), {})
        if poi_params:
            merged_params = dict(poi_params)
            merged_params.update(params)
            params = merged_params

        # Skip objects that netconvert placed on the wrong road.
        # If the object's OSM node id belongs to a known parent way and
        # that way does not match this road, leave the object so that
        # _add_missing_poi_signals can place it on the correct road.
        if parent_ways and road_way_id is not None:
            obj_id = obj.get("id", "")
            expected_ways = parent_ways.get(obj_id)
            if expected_ways and road_way_id not in expected_ways:
                continue

        # raw_type is usually the 'type' attribute from netconvert,
        # but for custom objects it might be the 'id'.
        raw_type = obj.get("id", "") if not obj.get("type") else obj.get("type", "")

        # Override with specific OSM tag if present
        osm_sign = params.get("osm.traffic_sign")
        osm_highway = params.get("osm.highway")

        # Use highway tag if we know it maps to a sign (e.g. give_way -> yield)
        if not osm_sign and osm_highway in ("give_way", "stop", "priority"):
            # Map OSM highway tags to generic internal types
            highway_to_type = {"give_way": "yield", "stop": "stop", "priority": "priority"}
            search_type = highway_to_type.get(osm_highway, raw_type)
        else:
            search_type = osm_sign if osm_sign else raw_type

        signal_type_id = None
        if search_type in mapping:
            signal_type_id = mapping[search_type]
        elif country and search_type.startswith(f"{country.upper()}:"):
            # Direct country code (e.g. SE:B3)
            signal_type_id = search_type

        if signal_type_id:
            # Create Signal
            signal = ET.SubElement(signals_elem, "signal")
            signal.set("id", obj.get("id", ""))
            signal.set("type", signal_type_id)
            signal.set("name", search_type)
            signal.set("s", obj.get("s", "0.0"))
            signal.set("t", obj.get("t", "0.0"))
            signal.set("dynamic", "no")
            signal.set("zOffset", "2.0")
            signal.set("country", country.upper())

            w, h = dimensions.get(signal_type_id, ("0.5", "0.5"))
            signal.set("width", w)
            signal.set("height", h)

            # Set orientation from OSM direction tag, falling back to t-coordinate
            try:
                t_val = float(obj.get("t", "0"))
            except (ValueError, TypeError):
                t_val = 0.0
            orientation = _get_signal_orientation(params, t_val)
            h_offset_deg = _get_sign_heading_offset_deg(params)
            if orientation == "-":
                h_offset_deg += 180.0
            signal.set("hOffset", f"{math.radians(h_offset_deg):.8f}")
            signal.set("pitch", "0.0")
            signal.set("roll", "0.0")
            signal.set("orientation", orientation)

            # Create Pole
            _add_pole(objects_elem, obj)
            poles_count += 1

            to_remove.append(obj)
            converted_count += 1

    for obj in to_remove:
        objects_elem.remove(obj)

    return converted_count, poles_count


def convert_objects_to_signals(
    xodr_file: Path,
    country: str = "SE",
    poi_file: Path | None = None,
    osm_file: Path | None = None,
    keep_netconvert_signals: bool = False,
) -> ConversionResult:
    """Convert traffic sign objects to OpenDRIVE signals in an XODR file.

    This function modifies the XODR file in place, converting objects
    with known traffic sign types to proper signal elements.

    Args:
        xodr_file: Path to the OpenDRIVE file to process.
        country: Country code for signal mapping.
        poi_file: Path to the POI file for metadata lookup.
        osm_file: Path to the original OSM file.
        keep_netconvert_signals: Whether to keep existing signals in the XODR.

    Returns:
        ConversionResult with success status and counts.
    """
    logger.info(f"Post-processing {xodr_file}...")

    if not xodr_file.exists():
        return ConversionResult(
            success=False,
            signals_converted=0,
            poles_added=0,
            error=f"File not found: {xodr_file}",
        )

    try:
        tree = ET.parse(xodr_file)
        root = tree.getroot()
    except ET.ParseError as e:
        return ConversionResult(
            success=False,
            signals_converted=0,
            poles_added=0,
            error=f"Failed to parse XML: {e}",
        )

    total_signals = 0
    total_poles = 0
    poi_params_by_id = _load_poi_params_by_id(poi_file)
    parent_ways = _load_osm_sign_parent_ways(osm_file) if osm_file else None

    for road in root.findall("road"):
        signals_elem = road.find("signals")
        if signals_elem is not None:
            if not keep_netconvert_signals:
                # Remove all implicit signals generated by netconvert
                # so we only keep the explicit ones from the OSM layer
                for sig in list(signals_elem):
                    signals_elem.remove(sig)
        else:
            signals_elem = ET.SubElement(road, "signals")

        objects_elem = road.find("objects")
        if objects_elem is None:
            continue

        road_way_id = _get_road_sumo_way_id(road)

        signals, poles = _process_signals(
            objects_elem,
            signals_elem,
            country=country,
            poi_params_by_id=poi_params_by_id,
            parent_ways=parent_ways,
            road_way_id=road_way_id,
        )
        total_signals += signals
        total_poles += poles

        # Remove empty objects element
        if len(objects_elem) == 0:
            road.remove(objects_elem)

    if poi_file is not None and poi_file.exists():
        added_signals, added_poles = _add_missing_poi_signals(
            root,
            poi_file,
            country,
            osm_file=osm_file,
        )
        total_signals += added_signals
        total_poles += added_poles

    # Always write to save deletions of implicit netconvert signals
    try:
        tree.write(xodr_file, encoding="UTF-8", xml_declaration=True)
        logger.info(
            f"Processed signals: kept {total_signals} explicit signs, added {total_poles} poles"
        )
    except Exception as e:
        return ConversionResult(
            success=False,
            signals_converted=total_signals,
            poles_added=total_poles,
            error=f"Failed to write file: {e}",
        )

    return ConversionResult(
        success=True,
        signals_converted=total_signals,
        poles_added=total_poles,
    )


# ---------------------------------------------------------------------------
# Dangling junction reference fix
# ---------------------------------------------------------------------------

_DANGLING_MATCH_TOLERANCE_M = 2.0


def _compute_road_endpoint(road: ET.Element, end: str) -> tuple[float, float] | None:
    """Compute the (x, y) world coordinates of a road's start or end point.

    For *start* this is simply the first geometry's (x, y).
    For *end* the last geometry's origin is projected forward by the remaining
    segment length along its heading (exact for lines; a linear approximation
    for curves, which is accurate enough for proximity matching).
    """
    pv = road.find("planView")
    if pv is None:
        return None
    geoms = pv.findall("geometry")
    if not geoms:
        return None

    if end == "start":
        g = geoms[0]
        return float(g.get("x", "0")), float(g.get("y", "0"))

    # end
    g = geoms[-1]
    x = float(g.get("x", "0"))
    y = float(g.get("y", "0"))
    hdg = float(g.get("hdg", "0"))
    road_length = float(road.get("length", "0"))
    seg_start_s = float(g.get("s", "0"))
    seg_len = road_length - seg_start_s
    return x + seg_len * math.cos(hdg), y + seg_len * math.sin(hdg)


def _fix_lane_links_for_endpoint(
    road: ET.Element,
    road_end: str,
    connected_road: ET.Element,
    contact_point: str,
) -> None:
    """Add predecessor/successor lane links for a newly connected road pair.

    Args:
        road: The road whose lane links are being updated.
        road_end: Which end of *road* is being connected ('start'|'end').
        connected_road: The road being connected to.
        contact_point: The contact end on *connected_road* ('start'|'end').
    """
    link_tag = "predecessor" if road_end == "start" else "successor"

    # Choose laneSection on the connected road matching the contact point.
    connected_lane_sections = connected_road.findall(".//laneSection")
    if not connected_lane_sections:
        return
    connected_ls = (
        connected_lane_sections[-1]
        if contact_point == "end"
        else connected_lane_sections[0]
    )
    connected_lane_ids = {
        lane.get("id")
        for lane in connected_ls.findall(".//lane")
        if lane.get("id") != "0"
    }

    # Choose the laneSection at the road end we're patching.
    our_lane_sections = road.findall(".//laneSection")
    if not our_lane_sections:
        return
    our_ls = (
        our_lane_sections[0] if road_end == "start" else our_lane_sections[-1]
    )

    for lane in our_ls.findall(".//lane"):
        lane_id = lane.get("id", "0")
        if lane_id == "0":
            continue

        # Prefer same-signed lane ID; fall back to opposite sign (reverse flow).
        if lane_id in connected_lane_ids:
            target_id = lane_id
        elif str(-int(lane_id)) in connected_lane_ids:
            target_id = str(-int(lane_id))
        else:
            continue

        lane_link = lane.find("link")
        if lane_link is None:
            lane_link = ET.SubElement(lane, "link")

        existing = lane_link.find(link_tag)
        if existing is not None:
            lane_link.remove(existing)

        new_link = ET.SubElement(lane_link, link_tag)
        new_link.set("id", target_id)


def fix_dangling_junction_refs(xodr_file: Path) -> int:
    """Fix roads with dangling (non-existent) junction references.

    ``netconvert`` sometimes generates roads whose ``<predecessor>`` or
    ``<successor>`` link points to a junction ID that has no corresponding
    ``<junction>`` definition in the output file.  Such roads are
    topologically isolated: the A* router cannot traverse them, which
    causes ``NetworkXNoPath`` when their spawn points are chosen.

    This function:

    1. Collects all junction IDs actually defined in the file.
    2. Identifies roads connected to *phantom* junctions (IDs not defined).
    3. Computes the geometric endpoint on the dangling side.
    4. Searches for another road endpoint within
       ``_DANGLING_MATCH_TOLERANCE_M`` metres.
    5. Replaces the phantom junction reference with a direct road-to-road
       link and updates lane ``<link>`` elements accordingly.

    The file is rewritten in place only when at least one fix is applied.

    Args:
        xodr_file: Path to the OpenDRIVE (.xodr) file.

    Returns:
        Number of road endpoint connections fixed (0 if nothing needed fixing).
    """
    if not xodr_file.exists():
        logger.warning(f"fix_dangling_junction_refs: file not found: {xodr_file}")
        return 0

    try:
        tree = ET.parse(xodr_file)
        root = tree.getroot()
    except ET.ParseError as e:
        logger.error(f"fix_dangling_junction_refs: failed to parse {xodr_file}: {e}")
        return 0

    # Step 1: Defined junction IDs (as strings, matching XML attribute values).
    defined_junctions: set[str] = {j.get("id", "") for j in root.findall("junction")}

    # Step 2: Find dangling endpoints — roads referencing non-existent junctions.
    # Each entry: (road_element, road_end: 'start'|'end', point: (x, y))
    DanglingEntry = tuple[ET.Element, str, tuple[float, float]]
    dangling: list[DanglingEntry] = []

    for road in root.findall("road"):
        # Junction connector roads are managed by junction elements; skip them.
        if road.get("junction", "-1") != "-1":
            continue
        link_elem = road.find("link")
        if link_elem is None:
            continue
        for link_tag, road_end in (("predecessor", "start"), ("successor", "end")):
            child = link_elem.find(link_tag)
            if child is None:
                continue
            if (
                child.get("elementType") == "junction"
                and child.get("elementId", "") not in defined_junctions
            ):
                pt = _compute_road_endpoint(road, road_end)
                if pt is not None:
                    dangling.append((road, road_end, pt))

    if not dangling:
        logger.debug("fix_dangling_junction_refs: no dangling junction references found")
        return 0

    logger.info(
        f"fix_dangling_junction_refs: found {len(dangling)} dangling "
        f"junction reference(s) across {len({r.get('id') for r, _, _ in dangling})} "
        f"road(s) in {xodr_file.name}"
    )

    # Step 3: Build a lookup of ALL road endpoints for partner search.
    AllEndpoint = tuple[ET.Element, str, tuple[float, float]]
    all_endpoints: list[AllEndpoint] = []
    for road in root.findall("road"):
        if road.get("junction", "-1") != "-1":
            continue
        for road_end in ("start", "end"):
            pt = _compute_road_endpoint(road, road_end)
            if pt is not None:
                all_endpoints.append((road, road_end, pt))

    # Step 4: Match each dangling endpoint to its geometric partner.
    fixes = 0
    matched_dangling_indices: set[int] = set()

    for idx, (road_a, end_a, pt_a) in enumerate(dangling):
        if idx in matched_dangling_indices:
            continue

        road_a_id = road_a.get("id", "")
        best_dist = _DANGLING_MATCH_TOLERANCE_M
        best_road_b: ET.Element | None = None
        best_end_b: str = ""

        for road_b, end_b, pt_b in all_endpoints:
            if road_b.get("id") == road_a_id:
                continue  # Skip self
            dist = math.hypot(pt_a[0] - pt_b[0], pt_a[1] - pt_b[1])
            if dist <= best_dist:
                best_dist = dist
                best_road_b = road_b
                best_end_b = end_b

        if best_road_b is None:
            logger.warning(
                f"fix_dangling_junction_refs: road {road_a_id} {end_a} endpoint "
                f"({pt_a[0]:.2f}, {pt_a[1]:.2f}) — no matching partner within "
                f"{_DANGLING_MATCH_TOLERANCE_M}m; leaving unchanged"
            )
            continue

        road_b_id = best_road_b.get("id", "")

        # Step 5: Patch road A's link (replace phantom junction with road ref).
        link_a = road_a.find("link")
        if link_a is None:
            link_a = ET.SubElement(road_a, "link")

        tag_a = "predecessor" if end_a == "start" else "successor"
        old_a = link_a.find(tag_a)
        if old_a is not None:
            link_a.remove(old_a)
        new_a = ET.SubElement(link_a, tag_a)
        new_a.set("elementType", "road")
        new_a.set("elementId", road_b_id)
        new_a.set("contactPoint", best_end_b)

        # Patch road B's link (add/replace its side of the connection).
        link_b = best_road_b.find("link")
        if link_b is None:
            link_b = ET.SubElement(best_road_b, "link")

        tag_b = "predecessor" if best_end_b == "start" else "successor"
        old_b = link_b.find(tag_b)
        if old_b is not None:
            # Only replace if it is also a phantom junction reference.
            if (
                old_b.get("elementType") == "junction"
                and old_b.get("elementId", "") not in defined_junctions
            ):
                link_b.remove(old_b)
            else:
                # Road B already has a valid link on this end; don't override.
                old_b = None  # sentinel: don't write new link on B

        if old_b is None and link_b.find(tag_b) is None:
            new_b = ET.SubElement(link_b, tag_b)
            new_b.set("elementType", "road")
            new_b.set("elementId", road_a_id)
            new_b.set("contactPoint", end_a)

        # Update lane links for both roads.
        _fix_lane_links_for_endpoint(road_a, end_a, best_road_b, best_end_b)
        _fix_lane_links_for_endpoint(best_road_b, best_end_b, road_a, end_a)

        # Mark paired dangling entry (if road_b also appeared in dangling list).
        for jdx, (rb, eb, _) in enumerate(dangling):
            if rb.get("id") == road_b_id and eb == best_end_b:
                matched_dangling_indices.add(jdx)
        matched_dangling_indices.add(idx)

        fixes += 1
        logger.info(
            f"fix_dangling_junction_refs: connected road {road_a_id} ({end_a}) "
            f"↔ road {road_b_id} ({best_end_b}), dist={best_dist:.3f}m"
        )

    if fixes > 0:
        try:
            tree.write(xodr_file, encoding="UTF-8", xml_declaration=True)
        except Exception as e:
            logger.error(f"fix_dangling_junction_refs: failed to write {xodr_file}: {e}")
            return 0

    return fixes
